export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const INCREASE_PRODUCT = 'INCREASE_PRODUCT';
export const DECREASE_PRODUCT = 'DECREASE_PRODUCT';